title: This is a Pages CMS site!
author:
  name: bkusuma
  email: your-email@domain.com
description: I've added a description!
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
header_pages:
  - about.md
minima:
  skin: auto
